spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/standard
    username: root
    password: root
    mvc:
      view:
        prefix: /templates/
        suffix: .html
server:
  port: 8080
  servlet:
    context-path: / # ÏîÄ¿Â·¾¶




